ALTER TABLE "companies"
ADD COLUMN "tagline" TEXT NOT NULL DEFAULT '',
ADD COLUMN "size" TEXT NOT NULL DEFAULT '',
ADD COLUMN "founded" INTEGER,
ADD COLUMN "values" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "perks" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
