ALTER TABLE "users"
ADD COLUMN "professionalRole" TEXT NOT NULL DEFAULT '',
ADD COLUMN "availability" TEXT NOT NULL DEFAULT '',
ADD COLUMN "profileIntro" TEXT NOT NULL DEFAULT '',
ADD COLUMN "salaryExpectation" TEXT NOT NULL DEFAULT '',
ADD COLUMN "profileStory" TEXT NOT NULL DEFAULT '',
ADD COLUMN "lookingFor" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "skills" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "profileLinks" JSONB,
ADD COLUMN "experiences" JSONB,
ADD COLUMN "selectedWork" JSONB;
